
language: node_js

node_js:
  - "node"
  - "8.11.1"

services:
  # - mongodb
  - docker

env:
  - VERSION="0.0.1"
  - DB_URI="mongodb://localhost"
  - DB_NAME="test"

# before_install:
  # - VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
  
  # - docker build -t api:latest .
  # - docker save --output api.tar api:latest
  # - scp -i $TRAVIS_DEPLOY_KEY api.tar root@165.227.23.80:/tmp
  # - ssh -i $TRAVIS_DEPLOY_KEY "docker load --input /tmp/api.tar"
  # - ssh -i $TRAVIS_DEPLOY_KEY "docker run -p="8080:8080" --expose="27017" --net="host" api:latest"

before_script:
    - yarn install
    - docker run -it -p 27017:27017 mongo:bionic mongod

script: yarn test